name: Verify Compiler
run-name: verify compiler functionalities
on: push

jobs:
    Build-Compiler:
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v4
            - run: cmake -S . -B out

            - name: build   # upload-artifact does not preserve the root dir so make a nested dir instead
              run: |
                cd out
                cmake --build .
                cd ..
                mkdir build
                mv out/* build
                mv build out
            
            - name: update build dir as artifact
              uses: actions/upload-artifact@v4
              with:
                name: build
                path: out/

    Lexer:
        runs-on: ubuntu-latest
        needs: Build-Compiler
        steps:
            - uses: actions/checkout@v4
            - name: download build dir
              uses: actions/download-artifact@v4
              with:
                name: build
            - name: test lexer
              run: |
                cd build
                ctest --verbose -R lexer