name: Verify Compiler
run-name: verify compiler functionalities
on: push

jobs:
    Build-Compiler:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cmake -S . -B build
            - run: cd build
            - run: make
    Lexer:
        runs-on: ubuntu-latest
        needs: Build-Compiler
        steps:
            - run: ctest --verbose -R lexer