name: Verify Compiler
run-name: verify compiler functionalities
on: push

jobs:
    Build-Compiler:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: cmake -S . -B build

            - name: build
              run: |
                cd build
                cmake --build .
            
            # New terminal. It's on the root directory.
            - name: update build dir as artifact
              uses: actions/upload-artifact@v4
              with:
                name: build
                path: build

    Lexer:
        runs-on: ubuntu-latest
        needs: Build-Compiler
        steps:
            - uses: actions/checkout@v2
            - name: download build dir
              uses: actions/download-artifact@v4
              with:
                name: build
            - name: test lexer
              run: |
                ls