name: Verify Compiler
run-name: verify compiler functionalities
on: push

jobs:
    Build-Compiler:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cmake -S . -B build

            - name: build
              run: |
                cd build
                cmake --build .

    Lexer:
        runs-on: ubuntu-latest
        needs: Build-Compiler
        steps:
            - uses: actions/checkout@v2
            - run: |
                cd build
                ctest --verbose -R lexer